<h1>Lab Assignment 9

In [1]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
A.diagonal().sum()

15

In [13]:
B = np.matrix('[1,2,3;4,5,6;6,7,8]')
B

matrix([[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]])

In [17]:
B.diagonal()

matrix([[1, 5, 8]])

In [45]:
lst =B.tolist()
lst

[[1, 2, 3], [4, 5, 6]]

In [46]:
lst =A.tolist()
lst

[1, 2, 3, 4, 5, 6]

In [36]:
lst=[1,2,3,4,5,6]

In [37]:
print(lst)

[1, 2, 3, 4, 5, 6]


In [38]:
A=np.array(lst)

In [39]:
A

array([1, 2, 3, 4, 5, 6])

In [40]:
type(A)

numpy.ndarray

In [41]:
lst=[[1,2,3],[4,5,6]]
lst

[[1, 2, 3], [4, 5, 6]]

In [42]:
B=np.matrix(lst)
B

matrix([[1, 2, 3],
        [4, 5, 6]])

## Lab 9
1. WAP to create a numpy array and find indices of non-zero elements
2. WAP to create a numpy to create a 3x3 identity matrix 
3. WAP to create a numpy to create a 3x3x3 array with random values
4. WAP to create a numpy to create a random vector of size 30 and find the mean value
5. WAP to create a numpy to multiply a 5x3 matrix by a 3x2 matrix 
6. WAP to create a numpy to input two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
7. WAP to print all the values of an array

<h1> 1.WAP to create a numpy array and find indices of non-zero elements

<h1>2. `WAP to create a numpy to create a 3x3 identity matrix

In [9]:
import numpy as np
array_2D=np.identity(3)
print('3x3 matrix:')
print(array_2D)


3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<h1>3.WAP to create a numpy to create a 3x3x3 array with random values

In [10]:
import numpy as np
x = np.random.random((3,3,3))
print(x)


[[[0.19509416 0.82876343 0.11981751]
  [0.34285528 0.42100752 0.78892869]
  [0.39109804 0.4837446  0.32415911]]

 [[0.97029635 0.32987964 0.67801292]
  [0.12720388 0.46115554 0.61664649]
  [0.28699879 0.1738107  0.74641258]]

 [[0.80740287 0.99084812 0.61631519]
  [0.93719775 0.53887182 0.00210735]
  [0.057233   0.44939262 0.86194555]]]


<h1>4.WAP to create a numpy to create a random vector of size 30 and find the mean value

In [11]:
Z = np.random.random(10)
m = Z.mean()
print (m)

0.4768423423680111


<h1>5.WAP to create a numpy to multiply a 5x3 matrix by a 3x2 matrix

In [12]:
import numpy as np
x = np.random.random((5,3))
print("First array:")
print(x)
y = np.random.random((3,2))
print("Second array:")
print(y)
z = np.dot(x, y)
print("Dot product of two arrays:")
print(z)


First array:
[[0.4275096  0.11103679 0.25241388]
 [0.58258162 0.43666898 0.2331312 ]
 [0.97667839 0.77258262 0.89020045]
 [0.26135208 0.96305808 0.19139878]
 [0.00214137 0.05107842 0.0266699 ]]
Second array:
[[0.49947674 0.980652  ]
 [0.92612346 0.0526972 ]
 [0.11159665 0.32681239]]
Dot product of two arrays:
[[0.34453342 0.50758146]
 [0.72141201 0.67051123]
 [1.30267841 1.2894231 ]
 [1.04380943 0.3695974 ]
 [0.05135076 0.01350768]]


<h1>6.WAP to create a numpy to input two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [13]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


<h1>7.WAP to print all the values of an array