<h1>Lab Assignment 4

In [1]:
l = list() #empty list
print (l)

[]


In [2]:
l = [1,2,3,4] #list of integers
print (l)

[1, 2, 3, 4]


In [3]:
l = [1,2,3, 4.5, 5.1] #list of numbers
print (l)

[1, 2, 3, 4.5, 5.1]


In [4]:
l = ["a","b",'c'] #list of characters
print (l)

['a', 'b', 'c']


In [5]:
l = [1,2,4.5,'abs',True] #mixed list
print (l)

[1, 2, 4.5, 'abs', True]


In [46]:
l = ["abc","pqr","xyz"] #list of strings
print (l)

['abc', 'pqr', 'xyz']


In [8]:
l=list('hello')
print(l)

['h', 'e', 'l', 'l', 'o']


In [6]:
s=('a','b','c','d','e')
l=list(s)
print(l)

['a', 'b', 'c', 'd', 'e']


In [7]:
l=list(input("Enter a list"))
print(l)

Enter a listDivya Jaiswal
['D', 'i', 'v', 'y', 'a', ' ', 'J', 'a', 'i', 's', 'w', 'a', 'l']


In [8]:
l=[1,[2,3],[4,5],[6,7,8],['Divya','Anu','Suchi']] #Nested List
print(l)

[1, [2, 3], [4, 5], [6, 7, 8], ['Divya', 'Anu', 'Suchi']]


In [9]:
len(l) #length of a list

5

In [10]:
l[3]  #indexing

[6, 7, 8]

In [15]:
l[2:4] #slicing

[[4, 5], [6, 7, 8]]

In [14]:
[-1,2,3] > [1,2,0]

False

In [17]:
[1,2,3] < [8,9,1]

True

In [2]:
l1=[1,2]
l2=[5,4,3]
l = l1+l2
print(l)

[1, 2, 5, 4, 3]


In [11]:
print(l*10) #Replicating a list

[1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3]


In [19]:
l=l*5
seq = l[2:15:3] #L[start:end:step]
print(seq)

[5, 1, 4, 2, 3]


In [20]:
l=l*4
print(l)
print(l[::3])

[1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 

In [21]:
l1=[1,2]
l2=[5,4,3]
l = l1+l2
l=l*3
print(l)
l[0:2] = ['one','two']
print(l)

[1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3]
['one', 'two', 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3]


In [22]:
l.append('new item') #add an element
print(l)

['one', 'two', 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 'new item']


In [23]:
l[3] = 'updated item' #replace an element
print(l)

['one', 'two', 5, 'updated item', 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 'new item']


In [24]:
del l[3]  #delete an item
print(l)

['one', 'two', 5, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 'new item']


In [27]:
del l[1]  #delete an item
print(l)

['one', 5, 'updated item', 3, 1, 2, 5, 4, 3, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 'new item']


In [25]:
l[5] = "item 1"
l[6] = "item2"
print(l)

['one', 'two', 5, 3, 1, 'item 1', 'item2', 4, 3, 1, 2, 5, 4, 3, 'new item']


In [26]:
del l[5:7]  #delete a slice
print(l)

['one', 'two', 5, 3, 1, 4, 3, 1, 2, 5, 4, 3, 'new item']


In [27]:
l.pop() #remove last element of the list
print(l)

['one', 'two', 5, 3, 1, 4, 3, 1, 2, 5, 4, 3]


In [29]:
l.pop(2) #removes an element at a position
print(l)

['one', 'two', 1, 4, 3, 1, 2, 5, 4, 3]


In [30]:
l.index(1) #prints an element at position x

2

In [31]:
t=['a','b','Banasthali',1,2,3]
l.extend(t)
print(l)

['one', 'two', 1, 4, 3, 1, 2, 5, 4, 3, 'a', 'b', 'Banasthali', 1, 2, 3]


In [32]:
l.insert(4,"Hello")
print(l)

['one', 'two', 1, 4, 'Hello', 3, 1, 2, 5, 4, 3, 'a', 'b', 'Banasthali', 1, 2, 3]


In [43]:
if 1 not in l:
    print("Element not found")
else:
    l.remove(1)
    print("Element Deleted")
print(l)

Element not found
['one', 'two', 4, 'Hello', 2, 5, 4, 'a', 'b', 'Banasthali', 2]


In [44]:
l.append(4)
l.count(4)

3

In [45]:
print(l)
l.reverse()
print(l)

['one', 'two', 4, 'Hello', 2, 5, 4, 'a', 'b', 'Banasthali', 2, 4]
[4, 2, 'Banasthali', 'b', 'a', 4, 5, 2, 'Hello', 4, 'two', 'one']


In [6]:
l1=[]'e','i','q','a','q','p','b']
l2=l1
l1.sort()
print(l1)
print(sorted(l2))

('e', 'i', 'q', 'a', 'q', 'p', 'b')
['a', 'b', 'e', 'i', 'p', 'q', 'q']


TypeError: 'tuple' object does not support item assignment

In [47]:
l.clear()
print(l)

[]


# Creating a Matrix

In [45]:
R = int(input("Enter the number of rows:")) 
C = int(input("Enter the number of columns:")) 
  
# Initialize matrix 
matrix = [] 
print("Enter the entries rowwise:") 
  
# For user input 
for i in range(R):          # A for loop for row entries 
    a =[] 
    for j in range(C):      # A for loop for column entries 
         a.append(int(input())) 
    matrix.append(a) 
  
# For printing the matrix 
for i in range(R): 
    for j in range(C): 
        print(matrix[i][j], end = " ") 
    print() 

Enter the number of rows:2
Enter the number of columns:2
Enter the entries rowwise:
1
2
3
4
1 2 
3 4 


# Lab 4
1. WAP to find minimum element from a list of integers alongwith its index in the list
2. WAP to calcualte mean of a given list of numbers
3. WAP to search an element in a list
4. WAP to count the frequency of an element in a list
5. WAP to find frequencies of all elements in a list
6. WAP to extact two slices from a list and add the slices and find which one is greater
7. WAP to find second largest number of a list
8. WAP to input a list of numbers and shift all zeros to the right and all non zeros to left of the list
9. WAP to add two matrices
10. WAP to multiply two matrices
11. WAP to print transpose of a matrix
12. WAP to add elements of diagonal of a matrix
13. WAP to find an element in a matrix
14. WAP to find inverse of a matrix

In [2]:
l=[15,6,9,1,0,8]
min=1000
for i in l:
    if i < min:
        min=i
idx=l.index(min)
print("Minimum Element is {}".format(min) , end = "\t")
print("Index is {}".format(idx))

Minimum Element is 0	Index is 4


<h1>1.WAP to find minimum element from a list of integers alongwith its index in the list

In [6]:
n=int(input("Enter no. of elements to input in list:"))
list=[]
for i in range(0,n):
    list.append(int(input()))
print(list)
min=1000
for i in list:
    if i < min:
        min=i
idx=list.index(min)
print("Minimum Element is {}".format(min) , end = "\t")
print("Index is", end=" ")
print(idx)

Enter no. of elements to input in list:5
10
22
11
5
3
[10, 22, 11, 5, 3]
Minimum Element is 3	Index is 4


<h1>2.WAP to calcualte mean of a given list of number

In [7]:
n=int(input("Enter the number of elements to be inserted: "))
a=[]
for i in range(0,n):
    elem=int(input("Enter element: "))
    a.append(elem)
print(a)
avg=sum(a)/n
print("Average of elements in the list",avg)

Enter the number of elements to be inserted: 5
Enter element: 0
Enter element: 5
Enter element: 2
Enter element: 3
Enter element: 10
[0, 5, 2, 3, 10]
Average of elements in the list 4.0


<h1>3.WAP to search an element in a list

In [5]:
L=[]
n=int(input("Enter the number of elements: "))
print("enter elements:")
for i in range(0,n):
    L.append(int(input()))
x=int(input("Enter elements to be searched:"))
found=0 
for i in range(n):
    if x==L[i]: 
        print("Item found at the Position : ",i+1)
        found=1
if found==0:
    print("Item not found in list")


Enter the number of elements: 5
enter elements:
1
2
5
3
0
Enter elements to be searched:5
Item found at the Position :  3


<h1>4.WAP to count the frequency of an element in a list

In [7]:
n=int(input("Enter number of element to be entered in the list:"))
list=[]
print("Enter elements:")
for i in range(n):
    list.append(int(input()))
print(list)
print("Enter the number of which you want to know thefrequency:")
x=int(input())
count=0
for i in range(n):
    if x==list[i]:
        count=count+1
        
print(x,"is present ",count,"times in the list!!")



Enter number of element to be entered in the list:10
Enter elements:
1
2
5
2
7
2
5
2
2
1
[1, 2, 5, 2, 7, 2, 5, 2, 2, 1]
Enter the number of which you want to know thefrequency:
2
2 is present  5 times in the list!!


<h1>5. WAP to find frequencies of all elements in a list

In [12]:
import collections
n=int(input("enter number of elements to be entered:"))
my_list = []
for i in range(n):
    my_list.append(int(input()))
print("Original List : ",my_list)
ctr = collections.Counter(my_list)
print("Frequency of the elements in the List : ",ctr)

enter number of elements to be entered:6
22
22
1
22
5
22
Original List :  [22, 22, 1, 22, 5, 22]
Frequency of the elements in the List :  Counter({22: 4, 1: 1, 5: 1})


<h1>6.WAP to extact two slices from a list and add the slices and find which one is greater

In [23]:
import math
n=int(input("Enter the number of elements to be inserted: "))
a=[]
for i in range(0,n):
    elem=int(input("Enter element: "))
    a.append(elem)
if n%2==0:
    d=(n//2)
    slice1=a[0:d]
    slice2=a[d:n]
else:
    print("List cannot be divided into two equal halves!! :(")
    
print("Two slices are:")
print(slice1)
print(slice2)
s1=0
s2=0
for i in range (d):
    s1+=slice1[i]
for i in range (d):
    s2+=slice2[i]
print("sum of slice 1 is:", s1)
print("sum of slice 2 is:", s2)
if s1>s2:
    
    print("slice 1 sum is greater")
else:
    
    print("slice 2 sum is greater")

Enter the number of elements to be inserted: 6
Enter element: 1
Enter element: 2
Enter element: 3
Enter element: 3
Enter element: 2
Enter element: 2
Two slices are:
[1, 2, 3]
[3, 2, 2]
sum of slice 1 is: 6
sum of slice 2 is: 7
slice 2 sum is greater


<h1>7.WAP to find second largest number of a list

In [24]:
a=[]
n=int(input("Enter number of elements:"))
for i in range(1,n+1):
    b=int(input("Enter element:"))
    a.append(b)
a.sort()
print("Second largest element is:",a[n-2])


Enter number of elements:5
Enter element:1
Enter element:2
Enter element:5
Enter element:11
Enter element:7
Second largest element is: 7


<h1> 8.WAP to input a list of numbers and shift all zeros to the right and all non zeros to left of the list

In [4]:
n=int(input("Enter number of elements to entered in the list:"))

list=[]
print("Enter elements:")
for i in range(0,n):
    list.append(int(input()))
r=[]
l=[]
for i in range(0,n):
    if list[i]==0:
        r.append(0)
    else:
        l.append(list[i])
ans=l+r
print("Required list will be:")
print(ans)

Enter number of elements to entered in the list:5
Enter elements:
1
0
5
0
2
Required list will be:
[1, 5, 2, 0, 0]


<h1> 9. WAP to add two matrices

In [1]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

for i in range(len(X)):
    for j in range(len(X[0])):
        result[i][j] = X[i][j] + Y[i][j]

for r in result:
    print(r)


[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


<h1> 10.WAP to multiply two matrices

In [2]:
# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]
# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]


for i in range(len(X)):
    for j in range(len(Y[0])):
        for k in range(len(Y)):
            result[i][j] += X[i][k] * Y[k][j]

for r in result:
    print(r)


[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


<h1>11.WAP to print transpose of a matrix

In [3]:


X = [[12,7],
    [4 ,5],
    [3 ,8]]

result = [[0,0,0],
         [0,0,0]]

for i in range(len(X)):

    for j in range(len(X[0])):
        result[j][i] = X[i][j]

for r in result:
    print(r)


[12, 4, 3]
[7, 5, 8]


<h1> 12.WAP to add elements of diagonal of a matrix

In [6]:
#sum of diagonal elements from upper left to lower right
mtrx = [[3, 1, 2], 
        [4, 11, 5], 
        [8, 0, 2]]
mtrxrows = len(mtrx)
mtrxcols = len(mtrx[0])
diagnl_sum = 0
for n in range(mtrxrows):
    for m in range(mtrxcols):
        if n == m:
            diagnl_sum += mtrx[n][m]
print("The Sum of all Diagonal elements of a given Matix = ", diagnl_sum)

The Sum of all Diagonal elements of a given Matix =  16


<h1>13.WAP to find an element in a matrix

In [4]:
R = int(input("Enter the number of rows:")) 
C = int(input("Enter the number of columns:")) 
  
# Initialize matrix 
matrix = [] 
print("Enter the entries rowwise:") 
  
# For user input 
for i in range(R):          # A for loop for row entries 
    a =[] 
    for j in range(C):      # A for loop for column entries 
        a.append(int(input())) 
    matrix.append(a) 
    
    
#For printing the matrix 
for i in range(R): 
    for j in range(C): 
        print(matrix[i][j], end = " ") 
    print() 


value=int(input("Enter element to be searched:"))
flag= False
for row in matrix:
    for element in row:
        if element == value:
            print(value,' is present in matrix in row ',row )
            flag=True
if flag==False:
    print("Entered element is not present")
            




Enter the number of rows:2
Enter the number of columns:2
Enter the entries rowwise:
1
2
4
2
1 2 
4 2 
Enter element to be searched:2
2  is present in matrix in row  [1, 2]
2  is present in matrix in row  [4, 2]


<h1>14.WAP to find inverse of a matrix

In [1]:
# Importing Library
import numpy as np

# inverse of 4X4 matrix
arr = np.array([[1, 2, 3, 4],
                [10, 11, 14, 25],
                [20, 8, 7, 55],
                [40, 41, 42, 43]])

inverse_array = np.linalg.inv(arr)
print("Inverse array is ")
print(inverse_array)


Inverse array is 
[[-15.07692308   4.9         -0.8         -0.42307692]
 [ 32.48717949 -10.9          1.8          1.01282051]
 [-20.84615385   7.1         -1.2         -0.65384615]
 [  3.41025641  -1.1          0.2          0.08974359]]
